import requests
import random


def move_multiplier(attacker, defender):
    type_chart = {
        "normal": {"normal": 1,
                   "fire": 1,
                   "water": 1,
                   "electric": 1,
                   "grass": 1,
                   "ice": 1,
                   "fighting": 1,
                   "poison": 1,
                   "ground": 1,
                   "flying": 1,
                   "psychic": 1,
                   "bug": 1,
                   "rock": 0.5,
                   "ghost": 0.5,
                   "dragon": 1,
                   "dark": 1,
                   "steel": 0.5,
                   "fairy": 1
                   },
        "fire": {"normal": 1,
                 "fire": 0.5,
                 "water": 0.5,
                 "electric": 1,
                 "grass": 2,
                 "ice": 2,
                 "fighting": 1,
                 "poison": 1,
                 "ground": 1,
                 "flying": 1,
                 "psychic": 1,
                 "bug": 2,
                 "rock": 0.5,
                 "ghost": 1,
                 "dragon": 0.5,
                 "dark": 1,
                 "steel": 2,
                 "fairy": 1
                 },
        "water": {"normal": 1,
                  "fire": 2,
                  "water": 0.5,
                  "electric": 1,
                  "grass": 0.5,
                  "ice": 1,
                  "fighting": 1,
                  "poison": 1,
                  "ground": 2,
                  "flying": 1,
                  "psychic": 1,
                  "bug": 1,
                  "rock": 2,
                  "ghost": 1,
                  "dragon": 0.5,
                  "dark": 1,
                  "steel": 1,
                  "fairy": 1
                  },
        "electric": {"normal": 1,
                     "fire": 1,
                     "water": 2,
                     "electric": 0.5,
                     "grass": 0.5,
                     "ice": 1,
                     "fighting": 1,
                     "poison": 1,
                     "ground": 0.5,
                     "flying": 2,
                     "psychic": 1,
                     "bug": 1,
                     "rock": 1,
                     "ghost": 1,
                     "dragon": 0.5,
                     "dark": 1,
                     "steel": 1,
                     "fairy": 1
                     },
        "grass": {"normal": 1,
                  "fire": 0.5,
                  "water": 2,
                  "electric": 1,
                  "grass": 0.5,
                  "ice": 1,
                  "fighting": 1,
                  "poison": 0.5,
                  "ground": 2,
                  "flying": 0.5,
                  "psychic": 1,
                  "bug": 0.5,
                  "rock": 2,
                  "ghost": 1,
                  "dragon": 0.5,
                  "dark": 1,
                  "steel": 0.5,
                  "fairy": 1
                  },
        "ice": {"normal": 1,
                "fire": 1,
                "water": 0.5,
                "electric": 1,
                "grass": 2,
                "ice": 0.5,
                "fighting": 1,
                "poison": 1,
                "ground": 1,
                "flying": 2,
                "psychic": 1,
                "bug": 1,
                "rock": 1,
                "ghost": 1,
                "dragon": 2,
                "dark": 1,
                "steel": 0.5,
                "fairy": 1
                },
        "fighting": {"normal": 2,
                     "fire": 1,
                     "water": 1,
                     "electric": 1,
                     "grass": 1,
                     "ice": 2,
                     "fighting": 1,
                     "poison": 0.5,
                     "ground": 1,
                     "flying": 0.5,
                     "psychic": 0.5,
                     "bug": 0.5,
                     "rock": 2,
                     "ghost": 0.5,
                     "dragon": 1,
                     "dark": 2,
                     "steel": 2,
                     "fairy": 0.5
                     },
        "poison": {"normal": 1,
                   "fire": 1,
                   "water": 1,
                   "electric": 1,
                   "grass": 2,
                   "ice": 1,
                   "fighting": 1,
                   "poison": 0.5,
                   "ground": 0.5,
                   "flying": 1,
                   "psychic": 1,
                   "bug": 2,
                   "rock": 0.5,
                   "ghost": 0.5,
                   "dragon": 1,
                   "dark": 1,
                   "steel": 0.5,
                   "fairy": 2
                   },
        "ground": {"normal": 1,
                   "fire": 2,
                   "water": 1,
                   "electric": 2,
                   "grass": 0.5,
                   "ice": 1,
                   "fighting": 1,
                   "poison": 2,
                   "ground": 1,
                   "flying": 0.5,
                   "psychic": 1,
                   "bug": 0.5,
                   "rock": 2,
                   "ghost": 1,
                   "dragon": 1,
                   "dark": 1,
                   "steel": 2,
                   "fairy": 1
                   },
        "flying": {"normal": 1,
                   "fire": 1,
                   "water": 1,
                   "electric": 0.5,
                   "grass": 2,
                   "ice": 1,
                   "fighting": 2,
                   "poison": 1,
                   "ground": 1,
                   "flying": 1,
                   "psychic": 1,
                   "bug": 2,
                   "rock": 0.5,
                   "ghost": 1,
                   "dragon": 1,
                   "dark": 1,
                   "steel": 0.5,
                   "fairy": 1
                   },
        "psychic": {"normal": 1,
                    "fire": 1,
                    "water": 1,
                    "electric": 1,
                    "grass": 1,
                    "ice": 1,
                    "fighting": 2,
                    "poison": 2,
                    "ground": 1,
                    "flying": 1,
                    "psychic": 0.5,
                    "bug": 1,
                    "rock": 1,
                    "ghost": 1,
                    "dragon": 1,
                    "dark": 0.5,
                    "steel": 0.5,
                    "fairy": 1
                    },
        "bug": {"normal": 1,
                "fire": 0.5,
                "water": 1,
                "electric": 1,
                "grass": 2,
                "ice": 1,
                "fighting": 0.5,
                "poison": 2,
                "ground": 1,
                "flying": 0.5,
                "psychic": 2,
                "bug": 1,
                "rock": 1,
                "ghost": 0.5,
                "dragon": 1,
                "dark": 2,
                "steel": 0.5,
                "fairy": 0.5
                },
        "rock": {"normal": 1,
                 "fire": 2,
                 "water": 1,
                 "electric": 1,
                 "grass": 1,
                 "ice": 2,
                 "fighting": 0.5,
                 "poison": 1,
                 "ground": 0.5,
                 "flying": 2,
                 "psychic": 1,
                 "bug": 2,
                 "rock": 1,
                 "ghost": 1,
                 "dragon": 1,
                 "dark": 1,
                 "steel": 0.5,
                 "fairy": 1
                 },
        "ghost": {"normal": 1,
                  "fire": 1,
                  "water": 1,
                  "electric": 1,
                  "grass": 1,
                  "ice": 1,
                  "fighting": 1,
                  "poison": 1,
                  "ground": 1,
                  "flying": 1,
                  "psychic": 1,
                  "bug": 1,
                  "rock": 1,
                  "ghost": 2,
                  "dragon": 1,
                  "dark": 0.5,
                  "steel": 1,
                  "fairy": 1
                  },
        "dragon": {"normal": 1,
                   "fire": 1,
                   "water": 1,
                   "electric": 1,
                   "grass": 1,
                   "ice": 1,
                   "fighting": 1,
                   "poison": 1,
                   "ground": 1,
                   "flying": 1,
                   "psychic": 1,
                   "bug": 1,
                   "rock": 1,
                   "ghost": 1,
                   "dragon": 2,
                   "dark": 1,
                   "steel": 0.5,
                   "fairy": 0.5
                   },
        "dark": {"normal": 1,
                 "fire": 1,
                 "water": 1,
                 "electric": 1,
                 "grass": 1,
                 "ice": 1,
                 "fighting": 0.5,
                 "poison": 1,
                 "ground": 1,
                 "flying": 1,
                 "psychic": 2,
                 "bug": 1,
                 "rock": 1,
                 "ghost": 2,
                 "dragon": 1,
                 "dark": 0.5,
                 "steel": 1,
                 "fairy": 0.5
                 },
        "steel": {"normal": 1,
                  "fire": 0.5,
                  "water": 0.5,
                  "electric": 0.5,
                  "grass": 1,
                  "ice": 2,
                  "fighting": 1,
                  "poison": 1,
                  "ground": 1,
                  "flying": 1,
                  "psychic": 1,
                  "bug": 1,
                  "rock": 2,
                  "ghost": 1,
                  "dragon": 1,
                  "dark": 1,
                  "steel": 0.5,
                  "fairy": 2
                  },
        "fairy": {"normal": 1,
                  "fire": 0.5,
                  "water": 1,
                  "electric": 1,
                  "grass": 1,
                  "ice": 1,
                  "fighting": 2,
                  "poison": 0.5,
                  "ground": 1,
                  "flying": 1,
                  "psychic": 1,
                  "bug": 1,
                  "rock": 1,
                  "ghost": 1,
                  "dragon": 2,
                  "dark": 2,
                  "steel": 0.5,
                  "fairy": 1
                  }
    }
    multiplier = type_chart[attacker][defender]
    return multiplier


request_pokemon = requests.get("https://pokeapi.co/api/v2/pokemon-species/?limit=151")
pokemon_content = request_pokemon.json()
# print(pokemon_content)
pokemon_data = pokemon_content["results"]


pokemon_names = []
for index in range(0, 151):
    pokemon_names.append(pokemon_data[index]["name"])
#     print(pokemon_names[index])


print(f"Pokemon to choose from: {pokemon_names}")


user_choosing = True
while user_choosing:
    user_input = input()
    user_pokemon = user_input.lower()
    if user_pokemon in pokemon_names:
        user_choosing = False
    else:
        print("Invalid, please try again")

ai_pokemon = random.choice(pokemon_names)

user_pokemon_request = requests.get(f"https://pokeapi.co/api/v2/pokemon/{pokemon_names.index(user_pokemon) + 1}")
user_pokemon_content = user_pokemon_request.json()
user_pokemon_stats = user_pokemon_content["types"][0]["type"]["name"]
print(f"Your pokemon: {user_pokemon}, type: {user_pokemon_stats}")
user_pokemon_speed = user_pokemon_content["stats"][6]["based"]["name"]

ai_pokemon_request = requests.get(f"https://pokeapi.co/api/v2/pokemon/{pokemon_names.index(ai_pokemon) + 1}")
ai_pokemon_content = ai_pokemon_request.json()
ai_pokemon_stats = ai_pokemon_content["types"][0]["type"]["name"]
print(f"Ai Pokemon: {ai_pokemon}, type {ai_pokemon_stats}")

move_order = random.randint(0, 1)
if move_order == 0:
    print("You attacked first:")
    end_condition(user_pokemon_stats, ai_pokemon_stats)
elif move_order == 1:
    print("Ai attacked first:")
    end_condition(ai_pokemon_stats, user_pokemon_stats)

# "stats":[{"base_stat":60,"effort":0,"stat":{"name":"hp","url":"https://pokeapi.co/api/v2/stat/1/"}},{"base_stat":62,"effort":0,"stat":{"name":"attack","url":"https://pokeapi.co/api/v2/stat/2/"}},{"base_stat":63,"effort":0,"stat":{"name":"defense","url":"https://pokeapi.co/api/v2/stat/3/"}},{"base_stat":80,"effort":1,"stat":{"name":"special-attack","url":"https://pokeapi.co/api/v2/stat/4/"}},{"base_stat":80,"effort":1,"stat":{"name":"special-defense","url":"https://pokeapi.co/api/v2/stat/5/"}},{"base_stat":60,"effort":0,"stat":{"name":"speed","url":"https://pokeapi.co/api/v2/stat/6/"}}]
# print(pokemon_data)
